### ISSUE TITLE
Hover tip on squawk code.

### ISSUE THREAD

**Issue by mindlesstux** [mindlesstux/dump1090#2]
http://en.wikipedia.org/wiki/Transponder_(aviation)

Seems like a reasonable list to implament.

**Comment by terribium** [comment]
These codes are quite area or country dependent. These explanations should be only shown if sure that it is correct. Since we have coordinates, validity should be somewhat easy to check.

**Comment by mindlesstux** [comment]
We could also use the location api of google maps api to possibly extract the right country too.

The assumption being that the airspace above the dump1090 station and the person viewing are in the same country.   This may not hold true to all cases, and think there is a limitation on the location api call count.

**Comment by mindlesstux** [comment]
Went with the basics, closing.
